[amr]
bx=4
by=4
bz=4
level_min=4
level_max=4
markers_kernel=RefineCondition_pseudo_gradient_rad
nbOctsPerGroup=1024
use_block_data=yes
loadbalance_coherent_levels = 3
enable_load_balance_during_init=false
epsilon_refine= 0.6
epsilon_coarsen= 0.4
error_min=0.2
error_max=0.8

# control MPI load balancing (number of time steps between two
# consecutive load balacing)
#load_balancing_frequency=50

# control AMR cycle frequence (number of time steps between two
# consecutive AMR cycles)
#cycle_frequency=1000000

[hydro]
gamma0               = 1.666        
niter_riemann        = 10
iorder               = 2
slope_type           = 2       
riemann              = hllc                
smallp               = 1e-18             
update               = HydroUpdate_RK2

[dt]
dt_kernel            = Compute_dt_rad
dt                   = 1.0e-4
particle_cfl         = 0.8
hydro_cfl            = 0.9

[mesh]
boundary_type_xmax   = reflecting          
boundary_type_xmin   = reflecting          
boundary_type_ymax   = reflecting            
boundary_type_ymin   = reflecting            
boundary_type_zmax   = reflecting            
boundary_type_zmin   = reflecting            
ndim                 = 3                   
xmin                 = 0.0      
xmax                 = 1.0                 
ymin                 = 0.0               
ymax                 = 1.0                 
zmin                 = 0.0     
zmax                 = 1.0

[run]               
enable_output        = true                
initial_conditions   = rad_blast
nstepmax             = 200000
output_frequency     = 100
nlog                 = 100
tend                 = 500.0
cosmo_proxy          = true

[rad]
update               = RadUpdate_euler_M1
box_size             = 6.6
temperature          = 1e4
xe_start             = 1.2e-3

[source_terms]
updates              = SourceUpdate_Ionization_Chem

[ionization]
rho_crit             = 8
ndot                 = 0.625e48
mode                 = stromgren
apply_cooling        = false
temp_black_body      = 50000
dynamic              = false
zre_start            = -1000.0

[cosmology]
clight_fraction      = 0.001

[output]
backend              = IOManager_hdf5      
checkpoint           = IOManager_checkpoint
debug                = false
hdf5_enabled         = yes
output_real_type     = float               
outputdir            = .             
outputprefix         = stromgren
outputVtkAscii       = true
outputVtkBinary      = true
outputVtkAppended    = true
vtk_enabled          = yes
write_mesh_info      = yes
write_variables      = rho,e_rad,xe,fx_rad,fy_rad,fz_rad,zre
