[run]
initial_conditions   = tiled_restart
tend             	= 200.0          	 
iter_start       	= 0

nlog             	= 10             	 
nstepmax         	= 100            	 

enable_checkpoint	= no            	 
enable_output    	= no

[mesh]
ndim             	= 3

boundary_type_xmax   = periodic       	 
boundary_type_xmin   = periodic       	 
boundary_type_ymax   = periodic       	 
boundary_type_ymin   = periodic       	 
boundary_type_zmax   = reflecting     	 
boundary_type_zmin   = reflecting     	 

xmax             	= <xmax>         	 
xmin             	= 0.0            	 
ymax             	= <ymax>          	 
ymin             	= 0.0            	 
zmax             	= 1.0            	 
zmin             	= 0.0  

[amr]
level_min        	= <level_min>
level_max        	= <level_max>

bx               	= 16             	 
by               	= 16             	 
bz               	= 16

coarse_oct_resolution_x = <cor_x>
coarse_oct_resolution_y = <cor_y>
coarse_oct_resolution_z = 2

cycle_frequency      	= 1
load_balancing_frequency = 100


markers_kernel   	= RefineCondition_downflows
downflow_sign    	= 1              	 
velocity_coarsen 	= -0.25          	 
velocity_refine  	= 0.75

[dt]
dt_kernel        	= Compute_dt_hydro,Compute_dt_parabolic
hydro_cfl        	= 0.8            	 
parabolic_cfl    	= 0.5

[restart]
filename         	= ./restart.h5 ; Default
nrep_x = <nrep_x>
nrep_y = <nrep_y>

###### Physics setup

[c91]
mpoly            	= 1.0            	 
pert_amplitude   	= 1.0e-5         	 
rho0             	= 10.0           	 
seed             	= 12345          	 
sigma            	= 1.0            	 
t0               	= 10.0
theta            	= 20.0

[cooling]
ff_fluxes        	= 1.4            	 
ff_layer         	= one_cell       	 
update           	= CoolingUpdate_FF    

[gravity]
gravity_type     	= 1              	 
gx               	= 0.0            	 
gy               	= 0.0            	 
gz               	= 40.0           	 

[hydro]
gamma0           	= 1.666666667    	 
problem          	= C91            	 
riemann          	= hllc           	 
update           	= HydroUpdate_euler   
well_balanced    	= on             	 

[thermal_conduction]
diffusivity_mode 	= constant       	 
kappa            	= 0.07           	 
update           	= ParabolicUpdate_explicit

[viscosity]
mu               	= 0.0028         	 
update           	= ParabolicUpdate_explicit