[run]                
tend=1.0          
#output_timeslice=0.01
output_timeslice=0.25
#output_frequency=1                
initial_conditions=heat_conduction                 
nstepmax=-1

[dt]
dt_kernel=Compute_dt_hydro,Compute_dt_parabolic
hydro_cfl=0.5
parabolic_cfl=0.5

[amr]
level_min=2
level_max=4
#level_min=4
#level_max=4

coarse_oct_resolution_y=2

bx=4                   
by=4                   

markers_kernel=RefineCondition_pseudo_gradient

epsilon_coarsen=0.05                
epsilon_refine=0.1                

cycle_frequency=10          
load_balancing_frequency=5000000                  

nboctspergroup=2048
remap=MapUserData_linear

[hydro]                
gamma0=1.666666667               
riemann=hllc        
update=HydroUpdate_euler        

[mesh]
ndim=2

xmin=0.0                 
xmax=1.0               

ymin=0.0                 
ymax=0.5

boundary_type_xmax=absorbing         
boundary_type_xmin=absorbing       

boundary_type_ymax=periodic            
boundary_type_ymin=periodic            

[thermal_conduction]
update=ParabolicUpdate_explicit
diffusivity_mode=analytical
kappa_mode=spitzer
kappa=1.0

bctc_xmin=temperature
bctc_xmax=temperature

bctc_xmin_val=0.1
bctc_xmax_val=1.0

[output]
outputdir=./                  
outputprefix=heat_conduction
write_variables=rho,rho_vx,e_tot