[run]
initial_conditions   = restart
nlog                 = 10                  
nstepmax             = 100
tend                 = 100.0

enable_checkpoint    = yes                 
checkpoint_timeslice = 100.0               

enable_output        = true                
output_timeslice     = 100.0

iter_start           = 0

[mesh]         
ndim                 = 3

boundary_type_xmax   = periodic            
boundary_type_xmin   = periodic            
boundary_type_ymax   = periodic            
boundary_type_ymin   = periodic            
boundary_type_zmax   = reflecting          
boundary_type_zmin   = reflecting

xmax                 = 4.0                 
xmin                 = 0.0                 
ymax                 = 4.0                 
ymin                 = 0.0                 
zmax                 = 1.0                 
zmin                 = 0.0    

[amr]
level_min            = 3
level_max            = 5

bx                   = 16                  
by                   = 16                  
bz                   = 16                  

coarse_oct_resolution_x = 8                   
coarse_oct_resolution_y = 8                   
coarse_oct_resolution_z = 2                   

cycle_frequency          = 1
load_balancing_frequency = 50

markers_kernel       = RefineCondition_downflows
downflow_sign        = 1                   
velocity_coarsen     = -0.25               
velocity_refine      = 0.75                


[dt]
dt_kernel            = Compute_dt_hydro,Compute_dt_parabolic
hydro_cfl            = 0.8                 
parabolic_cfl        = 0.5

[output]
backend              = IOManager_hdf5      
checkpoint           = IOManager_checkpoint
outputdir            = ./                  
outputprefix         = C91                 
write_particle_variables =                     
write_variables      = rho,rho_vx,rho_vy,rho_vz,e_tot,rank,level

[restart]
filename             = ./restart_C91_173366.h5 ; Default


###### Physics setup

[c91]
mpoly                = 1.0                 
pert_amplitude       = 1.0e-5              
rho0                 = 10.0                
seed                 = 12345               
t0                   = 10.0                
theta                = 20.0                

[cooling]
ff_fluxes            = 1.4                 
ff_layer             = one_cell            
update               = CoolingUpdate_FF    
     
[gravity]
gravity_type         = 1                   
gx                   = 0.0                 
gy                   = 0.0                 
gz                   = 40.0                

[hydro]
gamma0               = 1.666666667         
problem              = C91                 
riemann              = hllc                
update               = HydroUpdate_euler   
well_balanced        = on                     
                     
[thermal_conduction]
diffusivity_mode     = constant            
kappa                = 0.07                
update               = ParabolicUpdate_explicit

[viscosity]
mu                   = 0.0028              
update               = ParabolicUpdate_explicit
